### ISSUE TITLE
Warp sign

### ISSUE THREAD

**Issue by eyau77** [SuperMarcus/TouchIt#1]
Hi great plugin, works great for in world portals!
However, i tried a warp sign but it says "level not found", but it does.  Any suggestions?

**Comment by SuperMarcus** [comment]
Will, you could try using other provider instead of SQLite3. Like yaml.

**Comment by SuperMarcus** [comment]
And, actually other user send me this kind of error before, and they just change the name of that level in level.dat and it's work correctly.
