### ISSUE TITLE
Sign status "touchit loading"

### ISSUE THREAD

**Issue by ztdroider25** [SuperMarcus/TouchIt#3]
Everytime i make a world telelport portal the sign just says touchit loading in all caps.  It never changes to where it says tap to teleport and the player count.  Please help because this is really confusing all the people online because they dont know what sign to tap.

Thanks

**Comment by SuperMarcus** [comment]
If could, change the name of that level in level.dat. You could use NBTExplorer to open that file.

**Comment by ztdroider25** [comment]
Ok thanks, ill try ut tonight.

**Comment by ztdroider25** [comment]
I changed the level name, the signs didnt change when I recreated them with the new names.

**Comment by SuperMarcus** [comment]
Did you use any non-ascii characters to name that level? Some provider may not support those words.

**Comment by ztdroider25** [comment]
No, the levels are:
- Lobby
- Creative 1
- Creative 2
- Creative 3
  The signs dont work right on any of them.

**Comment by SuperMarcus** [comment]
What about other provider? Have you tried using YAML?

**Comment by ztdroider25** [comment]
Yes, i tried YAML because i do not have  a MySQL i donr even know what
MySQL even is.

**Comment by ztdroider25** [comment]
I fixed it.  I had to make the sign say touchit&w in all caps, and leave the 3rd line blank (the world description line) then it worked.

**Comment by SuperMarcus** [comment]
Great:)
