### ISSUE TITLE
Get exception when creating sign to other world

### ISSUE THREAD

**Issue by tedenda** [SuperMarcus/TouchIt#4]
I get this error in console when I try to maka a sign to another world:
20:57:34 [CRITICAL] Could not pass event pocketmine\event\block\SignChangeEvent to TouchIt v1.1 Alpha: Undefined offset: 1 on TouchIt\Listener\SignCreateListener
20:57:34 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/TouchIt_v1.1 Alpha.phar/src/TouchIt/Listener/SignCreateListener" at line 102

I am running PocketMine-MP version 1.4.1dev-974

**Comment by tedenda** [comment]
I want to add that It is only when creating portal to other world this happens.
When creating portals sign to sign, no problem!
When creating Command sign, no problem!

**Comment by SuperMarcus** [comment]
I see. It seems like PocketMine API has been changed and I haven't got much time to update this plugin. But I will try to spend some time to fix this.

**Comment by ztdroider25** [comment]
@SuperMarcus  can you let me know where this function is located in the code? I am still learning PHP but I know enough that I can fix this bug if im pointed in the right direction.  This plugin is really really useful [and i mean that :)] but it is pretty much useless until this bug is patched.

**Comment by SuperMarcus** [comment]
Try the new version now
